"""
Configuration Génération 1 - Test initial des paramètres
"""

CONFIGS = [
    {
        "name": "A_baseline",
        "brightness": 1.0,
        "saturation": 2.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "B_sat_plus",
        "brightness": 1.0,
        "saturation": 2.5,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "C_sat_max",
        "brightness": 1.0,
        "saturation": 3.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "D_contrast_plus",
        "brightness": 1.0,
        "saturation": 2.0,
        "contrast": 2.0,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "E_hue_strict",
        "brightness": 1.0,
        "saturation": 2.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 8,
        "hue_low2": 165, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "F_sat_strict",
        "brightness": 1.0,
        "saturation": 2.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 60,
        "val_min": 40,
    },
    {
        "name": "G_sat_very_strict",
        "brightness": 1.0,
        "saturation": 2.5,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 80,
        "val_min": 40,
    },
    {
        "name": "H_val_strict",
        "brightness": 1.0,
        "saturation": 2.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 60,
    },
    {
        "name": "I_bright_plus",
        "brightness": 1.3,
        "saturation": 2.0,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 12,
        "hue_low2": 155, "hue_high2": 180,
        "sat_min": 40,
        "val_min": 40,
    },
    {
        "name": "J_combo1",
        "brightness": 1.2,
        "saturation": 2.5,
        "contrast": 1.8,
        "hue_low1": 0, "hue_high1": 10,
        "hue_low2": 160, "hue_high2": 180,
        "sat_min": 60,
        "val_min": 50,
    },
    {
        "name": "K_combo2",
        "brightness": 1.0,
        "saturation": 3.0,
        "contrast": 2.0,
        "hue_low1": 0, "hue_high1": 8,
        "hue_low2": 165, "hue_high2": 180,
        "sat_min": 70,
        "val_min": 40,
    },
    {
        "name": "L_combo3",
        "brightness": 1.1,
        "saturation": 2.5,
        "contrast": 1.5,
        "hue_low1": 0, "hue_high1": 15,
        "hue_low2": 150, "hue_high2": 180,
        "sat_min": 50,
        "val_min": 50,
    },
]
